eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:1010/eureka}
      
okta:
  oauth2:
    issuer: ${ISSUER_URI}
    audience: ${AUDIENCE}     
